# Generated by Django 5.1.8 on 2025-04-30 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0002_rename_stortemplates_storetemplates'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorePopup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('setting', models.JSONField()),
                ('active', models.BooleanField(default=False)),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_popup', to='stores.store')),
            ],
        ),
        migrations.CreateModel(
            name='Popup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('default_setting', models.JSONField()),
                ('code', models.CharField()),
                ('store_popup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='popup', to='popup.storepopup')),
            ],
        ),
    ]
