# Generated by Django 5.1.8 on 2025-05-02 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0003_rename_udated_store_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Popup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('default_setting', models.JSONField()),
                ('code', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='StorePopup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_url', models.URLField()),
                ('name', models.CharField(blank=True, max_length=50)),
                ('setting', models.JSONField(blank=True, null=True)),
                ('active', models.BooleanField(default=False)),
                ('updated_at', models.DateField(auto_now=True)),
                ('popup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_popup', to='popup.popup')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_popup', to='stores.store')),
            ],
        ),
    ]
