# Generated by Django 5.1.8 on 2025-04-20 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('icon', models.ImageField(upload_to='app_section')),
                ('order', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('icon', models.ImageField(upload_to='category')),
                ('order', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AppTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('display_name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='app_template')),
                ('active', models.BooleanField(default=False)),
                ('components', models.JSONField()),
                ('order', models.PositiveIntegerField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_template', to='stores.appsection')),
            ],
        ),
        migrations.AddField(
            model_name='appsection',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section', to='stores.category'),
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('domain', models.CharField(max_length=50)),
                ('store_api_key', models.CharField(max_length=50)),
                ('applied_date', models.DateField()),
                ('store_hash_value', models.CharField(max_length=50)),
                ('notification_service_api_key', models.CharField(max_length=50)),
                ('notification_service_auth_key', models.CharField(max_length=50)),
                ('created', models.DateField(auto_now_add=True)),
                ('udated', models.DateField(auto_now=True)),
                ('setting_has_changes', models.BooleanField()),
                ('setting_has_value', models.BooleanField()),
                ('setting_file', models.FileField(upload_to='store')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='store', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StorTemplates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('components', models.JSONField()),
                ('components_backup', models.JSONField()),
                ('order', models.PositiveIntegerField()),
                ('app_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_templates', to='stores.appsection')),
                ('app_templates', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_templates', to='stores.apptemplate')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_templates', to='stores.store')),
            ],
        ),
    ]
