# Generated by Django 5.1.8 on 2025-04-28 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StorTemplates',
            new_name='StoreTemplates',
        ),
    ]
