# Generated by Django 5.1.8 on 2025-04-22 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsection',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='app_section'),
        ),
        migrations.AlterField(
            model_name='appsection',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='apptemplate',
            name='display_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='apptemplate',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='app_template'),
        ),
        migrations.AlterField(
            model_name='apptemplate',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='store',
            name='applied_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='domain',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='store',
            name='notification_service_api_key',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='store',
            name='notification_service_auth_key',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='store',
            name='setting_file',
            field=models.FileField(blank=True, null=True, upload_to='store'),
        ),
        migrations.AlterField(
            model_name='store',
            name='setting_has_changes',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='store',
            name='setting_has_value',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_api_key',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_hash_value',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='stortemplates',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
