# Generated by Django 5.1.8 on 2025-04-30 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_rename_stortemplates_storetemplates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='udated',
            new_name='updated',
        ),
    ]
