# Generated by Django 5.1.8 on 2025-06-04 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_meta',
            field=models.BooleanField(default=False),
        ),
    ]
